sudo: require
services:
    - docker

before_install:
    - docker build -t dvaqueiro/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true dvaqueiro/react-test npm test -- --coverage

after_success:
    - docker build -t dvaqueiro/multi-client ./client
    - docker build -t dvaqueiro/multi-nginx ./nginx
    - docker build -t dvaqueiro/multi-server ./server
    - docker build -t dvaqueiro/multi-worker ./worker
      # Login in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push then to docker hub
    - docker push dvaqueiro/multi-client
    - docker push dvaqueiro/multi-nginx
    - docker push dvaqueiro/multi-server
    - docker push dvaqueiro/multi-worker
